stages:
  - build
  - deploy

compile:
  stage: build
  script: docker build -t brobot-template .
    
run:
  stage: deploy
  before_script:
    - docker info
  script:
    - echo -e "docker stop brobot-container\nexit 0" | bash
    - echo -e "docker remove brobot-container\nexit 0" | bash
    - >
      docker run -d --restart unless-stopped
      --env TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      --mount type=volume,source=brobot-volume,target=/app/data
      --name brobot-container brobot-template
  environment:
    name: production
  only: 
    - master
