stages:
#  - test
  - build
  - deploy

# TODO: add back in
#format:
#  stage: test
#  tags:
#    - docker
#  image: golang:1.13.5-alpine
#  script:
#    - go fmt
#    - go vet
#    - go test

compile:
  stage: build
#  tags: 
#    - shell
  script: docker build -t brobot-template .
    
run:
  stage: deploy
#  tags: 
#    - shell
  before_script:
    - docker info
  script:
    - echo -e "docker stop brobot-container\nexit 0" | bash
    - >
      docker run -d --restart unless-stopped
      -e TELEGRAM_TOKEN $TELEGRAM_TOKEN
      -- mount source=brobot-volume, target=/data
      -- name brobot-container brobot-template
  environment:
    name: production
  only: 
    - master