stages:
  - test
  - build
  - deploy

format:
  stage: test
  tags: 
    - docker
  image: golang:alpine-1.13.5
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  tags: 
    - shell
  script: docker build -t brobot-template .
    
run:
  stage: deploy
  tags: 
    - shell
  script:
    - echo -e "docker stop brobot-container\nexit 0" | bash
    - >
      docker run -d --restart unless-stopped
      -e TELEGRAM_TOKEN $TELEGRAM_TOKEN
      -- mount source=brobot-volume, target=/data
      -- name brobot-container brobot-template
  environment:
    name: production
  only: 
    - master